#!/bin/bash
#字体颜色
red="\e[31;1m"      #红
green="\e[32;1m"   #绿
yellow="\e[33;1m"  #黄
blue="\e[34;1m"    #蓝
purple="\e[35;1m"    #紫红
cyanine="\e[36;1m"    #青蓝
white="\e[0m"


msg() { clear;echo -e "\n\t\t$blue[*]$white$1$2$white\n" ;:;}  ##自定义通告颜色
enter() { echo -en "\n\n$green按回车继续$white";read op ;:;}  ##

msg $red "添加新用户"
sleep 1
_add(){
	export LC_ALL=zh_CN.UTF-8 
	
	USER=$(dialog --clear --title "Finish ubuntu20.04 Install" \
		--inputbox "输入你的用户名：
		(注：用户名只能为英文，且不含空格)" 8 50 \
		3>&1 1>&2 2>&3 3>&-)
	
	if [ -z $USER ];then
		clear
		echo -e "\n\n$red用户名不能为空！$white" 
		sleep 2
		return
	fi
	
	if [[ ! $USER =~ ^[a-zA-Z]+$ ]];then
		clear
		echo -e "\n\n$red用户名含非法字符！$white" 
		sleep 2
		return
	fi
	
	PASSWORD=$(dialog --clear --title "Finish ubuntu20.04 Install" \
	  --insecure \
	  --passwordbox "为$USER用户设置密码：
	  (6个数字，且不含空格):" 8 50 \
	  3>&1 1>&2 2>&3 3>&- )
	
	if [ -z $PASSWORD ];then
		clear
		echo -e "\n\n$red密码不能为空！$white" 
		sleep 2
		return
	fi
	
	expr $PASSWORD + 1 &> /dev/null
	if [ ! $? == 0 ];then
		clear
		echo -e "\n\n$red密码含非法字符！$white" 
		sleep 2
		return
	fi
	
	if [ ! ${#PASSWORD} -eq 6 ];then
		clear
		echo -e "\n\n$red密码为6位！请重新设置。$white" 
		sleep 2
		return		
	fi

	echo -e "$PASSWORD\n$PASSWORD" > $(dirname $0)/.PASSWORD
	echo "$USER" > $(dirname $0)/.USER
	passwd root < $(dirname $0)/.PASSWORD 1> /dev/null 2>&1
	
	#添加用户，设置密码
	useradd -m -G sudo -s /bin/bash -U $USER 1> /dev/null 2>&1
	chfn -f "$USER" $USER 1> /dev/null 2>&1 
	
	mkdir -p /home/$USER/.vnc
	passwd $USER < $(dirname $0)/.PASSWORD 1> /dev/null 2>&1
	
	sed -i "/^root/a $USER ALL=(ALL:ALL) ALL" /etc/sudoers
	#systemctl disable systemd-resolved.service 1> /dev/null 2>&1
	rm -rf /var/log/*
	
	echo "export DISPLAY=:1" >> /root/.bashrc && echo "export DISPLAY=:1" >> /home/$USER/.profile
	touch /home/hzt/.hushlogin
	echo "exec su - $USER; exit" > ~/.bash_profile
	
	if [ -e /etc/ssh/sshd_config ]
	then
		sed -i s/"PermitRootLogin yes"/"#PermitRootLogin prohibit-password"/g /etc/ssh/sshd_config
	fi
	
	msg $red "添加新用户$USER成功"
	sleep 1
	echo "vnc start " >> /home/$USER/.profile
	cat <<-EOF >"/home/$USER/.bash_profile"
	#!/bin/bash
	rm -rf /etc/resolv.conf
	echo 'nameserver 8.8.8.8' >> /etc/resolv.conf
	vnc
	rm -rf ~/.bash_profile
	EOF
	
	
	
	chmod +x "/home/$USER/.bash_profile"
	
	##自定义
	msg $red "请记住（或截图保存）以下信息"
	echo -e "\n\n\n\n\n\t\t根用户：root\n\t\t密码：$PASSWORD\n\n\t\t新加用户：$USER\n\t\t密码：$PASSWORD\n\n\t\tVNC默认连接地址信息：\n\t\t地址：127.0.0.1:5901\n\t\t密码：$PASSWORD"
	enter
	
	exec su - $USER

	exit
	
}




while :
do
	_add
done

