#!/bin/bash
#字体颜色
red="\e[31;1m"      #红
green="\e[32;1m"   #绿
yellow="\e[33;1m"  #黄
blue="\e[34;1m"    #蓝
purple="\e[35;1m"    #紫红
cyanine="\e[36;1m"    #青蓝
white="\e[0m"

CONFIG=/usr/local/bin/.config

msg() { clear;echo -e "\n\t\t$blue[*]$white$1$2$white\n" ;:;}  ##自定义通告颜色




_login(){
	i=0
	str=""
	label=('|' '/' '-' '\\')
	index=0
	while [ $i -le 20 ]
	do
		let index=i%4
		let jinshu=$i*5
		printf "\e[0m\e[32m[%-20s]\e[0m\e[0;32m[%c]\e[1;0m\e[0;35m[%-3d%%]\e[1;0m\r" $str ${label[$index]} $jinshu
		let i++
		str+="#"
		sleep 0.1
	done
	echo
}


_start(){
	clear
	echo -e "\n$red密码为$green$USER$red的密码$white"
	sudo echo 
	service dbus restart
	service dbus stop
	dbus-daemon --system
	service dbus status 
	
	##启动tigervnc 
	vncserver -kill :1  > /dev/null 2>&1
	source $CONFIG
	LD_PRELOAD=/lib/aarch64-linux-gnu/libgcc_s.so.1 vncserver -localhost no -depth 24 -name remote-desktop $GEO :$PORT
	
	##启动xrdp
	if [ ! -z "$(command -v xrdp)" ];then
		xrdp -k
		rm -rf /var/run/xrdp/xrdp-sesman.pid
		rm -rf /var/run/xrdp/xrdp.pid
		sudo service xrdp restart
		sleep 0.9
		sudo service xrdp status
	fi
	
	service --status-all

	[ ! -e "/data/data/com.termux/files/home/storage/shared/swap" ]&&mkdir /data/data/com.termux/files/home/storage/shared/swap
	[ ! -e "`echo ~/Desktop/MTS`" ]&&mkdir ~/Desktop/MTS
	[ ! -L "`echo ~/Desktop/MTS/swap`" ]&&ln -s /data/data/com.termux/files/home/storage/shared/swap ~/Desktop/MTS
	[ ! -L "`echo ~/Desktop/MTS/Download`" ]&&ln -s /data/data/com.termux/files/home/storage/shared/Download ~/Desktop/MTS
	#[ ! -L "`echo ~/Desktop/MTS/QQfile_recv`" ]&&ln -s /data/data/com.termux/files/home/storage/shared/Android/data/com.tencent.mobileqq/Tencent/QQfile_recv ~/Desktop/MTS
	if [ ! -e "`echo ~/Desktop/MTS/说明.txt`" ];then
		touch ~/Desktop/MTS/说明.txt
		cat <<-EOF >~/Desktop/MTS/说明.txt
		|************************|
		PS：1.这个MTS目录是连接到手机存储目录的交换区。
			 2.方便非Root用户存取文件，和交换文件。
			 3.每一次开机都会自动创建这个目录，不用担心它被删除。
			 
		使用方法：step1.在你手机自带的文件管理器找到 MTS 这个目录。
				   step2.把你下载的刘德华最新歌曲mp3文件，复制一份到这个目录。
				   step3.打开你的ubuntu系统，在桌面点击 MTS 目录就可以看见你的mp3歌曲了。
				   
		注意：同样的，你也可以把ubuntu里面的办公文件移动到 MTS 这个目录，然后去你手机文
			  件管理器就可以轻松获取到你的办公文件了
			  
		优点：解决了虚拟机与物理机文件交换繁杂的问题。
		待改进：解除安卓11系统限制访问data文件夹
		
		|************************|
		关于输入法说明：
				1）切换中/英 快捷键是 Ctrl+空格
		
		
		手机QQ接收的文件在下面这个目录（暂未实现链接到达本机）
		/storage/emulated/0/Android/data/com.tencent.mobileqq/Tencent/QQfile_recv/
		EOF
	fi
	
	_login
	msg $green "ubuntu20.04开机完毕·欢迎~"
	echo -e "\t$red获取更多帮助请使用命令 ubuntu$white"
}


_stop(){
	USER=$(whoami)
	msg $red "VNC服务列表如下："
	vncserver -list
	echo -n "输入需要杀死的端口号(示例:3):"
	read pt
	echo " "
	echo "已杀死的端口 $pt"
	vncserver -kill :$pt
	rm -rf /tmp/.X$pt-lock
	rm -rf /tmp/.X11-unix/X$pt
}


_PWD(){
	read -sp '请提供一个新的VNC密码: ' PASSWORD
	vncpasswd -f <<<"$PASSWORD\n$PASSWORD" > $HOME/.vnc/passwd
	msg $green "VNC登录密码已修改！"
}




_DPI(){
	export USER=$(whoami)
	export LC_ALL="zh_CN.UTF-8"
	HEIGHT=0
	WIDTH=0
	CHOICE_HEIGHT=5
	BACKTITLE="VNC 分辨率选择"
	TITLE="vncserver-start"
	MENU="请选择你的分辨率"
	export PORT=1
	
	OPTIONS=(
         1 "QHD 2k画质(2560x1600)"
         2 "FHD 1080p画质(1920x1080)"
         3 "HD-ready 高清画质(1280x720)"
         4 "自动画质"
         5 "自定义画质/端口")

	CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

	clear
	case $CHOICE in
        1)
            echo "你选择了QHD 2k画质(2560x1600)"
            sed -i "s#`cat $CONFIG | grep "GEO=" |awk -F '"' '{print $2}'`#-geometry 2560x1600#g" $CONFIG
            ;;
        2)
            echo "你选择了FHD 1080p画质(1920x1080)"
            sed -i "s#`cat $CONFIG | grep "GEO=" |awk -F '"' '{print $2}'`#-geometry 1920x1080#g" $CONFIG
            ;;
        3)
            echo "你选择了HD-ready 高清画质(1280x720)"
            sed -i "s#`cat $CONFIG | grep "GEO=" |awk -F '"' '{print $2}'`#-geometry 1280x720#g" $CONFIG
            ;;
        4)
            echo "你选择了自动画质"
			sed -i "s#`cat $CONFIG | grep "GEO=" |awk -F '"' '{print $2}'`##g" $CONFIG
            ;;
        5)
            echo "您选择手动提供 分辨率/端口"
            echo "输入您的自定义分辨率格式WIDTHxHEIGHT即1920x1200"
            echo -ne "分辨率：" ""
            read custom
            echo "输入您的自定义端口，即2" 
            echo -ne "端口：" ""
            read port
            sed -i "s#`cat $CONFIG | grep "GEO=" |awk -F '"' '{print $2}'`#-geometry $custom#g" $CONFIG
            #echo "GEO=\"-geometry $custom\"" > $CONFIG
            #echo "PORT=$port" >> $CONFIG
            sed -i "s#`cat $CONFIG | grep "PORT="`#PORT=$port#g" $CONFIG
            ;;
	esac	
}

_xfce(){
	[ ! -e $CONFIG ]&&touch $CONFIG
    echo 'GEO="-geometry 2560x1600"' >> $CONFIG
    echo 'PORT=1' >> $CONFIG

	msg $red "安装xfce桌面"
	echo -e "$red请输入root用户的密码：$white"
	sudo apt purge dialog -y

	sudo  apt install eatmydata -y
	sudo eatmydata apt install software-properties-common -y
	sudo add-apt-repository ppa:xubuntu-dev/staging -y
	sudo apt-get update
	
	sudo eatmydata apt install keyboard-configuration -y
	sudo eatmydata apt install tzdata -y
	sudo eatmydata apt install sudo wget nano inetutils-tools dialog bc dbus-x11 -y 
	sudo eatmydata apt install xfce4 xfce4-goodies xfce4-terminal exo-utils tigervnc-standalone-server tigervnc-common  ffmpeg  language-pack-en --no-install-recommends -y
	sudo eatmydata apt clean git -y
	
	mkdir -p ~/.vnc
	USER=`cat /usr/local/bin/.USER`
	LD_PRELOAD=/lib/aarch64-linux-gnu/libgcc_s.so.1 vncpasswd -f <<< `cat /usr/local/bin/.PASSWORD` > "/home/$USER/.vnc/passwd"
	rm -rf /usr/local/bin/.PASSWORD

	#/usr/bin/vncpasswd -f <<<"$PASSWORD\n$PASSWORD" > "/home/$USER/.vnc/passwd"
	#vncpasswd -f <<<"$PASSWORD"$'\n'"$PASSWORD" > /root/.vnc/passwd 

	cat <<-EOF > ~/.vnc/xstartup
	#!/bin/bash
	[ -r \$HOME/.Xresources ] && xrdb \$HOME/.Xresources
	export PULSE_SERVER=127.0.0.1
	XAUTHORITY=\$HOME/.Xauthority
	export XAUTHORITY
	#LANG=en_US.UTF-8
	#export LANG
	echo \$\$ > /tmp/xsession.pid
	dbus-launch --exit-with-session startxfce4 &
	EOF
	
	for x in fonts-wqy-microhei  libglu1-mesa bsdmainutils xdg-utils libxslt-dev libxml2-dev python3-pyqt5 ttf-mscorefonts-installer man-db vim
	do
		sudo eatmydata apt install "$x" -y
	done
	
	##安装fcitx
	sudo eatmydata apt purge ibus -y
	sudo eatmydata apt install fcitx fcitx-ui-qimpanel -y
	sudo eatmydata apt install fcitx-bin -y
	sudo eatmydata apt install fcitx-table -y
	sudo eatmydata apt install fcitx-pinyin -y
	#sudo eatmydata apt remove fcitx-ui-classic -y
	im-config fcitx
	sudo cp /usr/share/fcitx/xdg/autostart/fcitx-autostart.desktop /etc/xdg/autostart/

	echo "export DISPLAY=\":1\"" >> /etc/profile
	source /etc/profile
	
	[ -z "`dpkg -l | grep fonts-wqy-microhei`" ]&&sudo apt-get install fonts-wqy-microhei -y
	[ ! -z "`cat /etc/locale.gen|grep '# zh_CN.UTF-8 UTF-8'`" ]&&sed -i "s/# zh_CN.UTF-8 UTF-8/ zh_CN.UTF-8 UTF-8/g" /etc/locale.gen
	locale-gen
	echo "export LC_ALL=zh_CN.UTF-8" >> ~/.bashrc
	
	cat <<-EOF>> /etc/environment
	TMOE_PROOT=true
	MOZ_FAKE_NO_SANDBOX=1
	QT_QPA_PLATFORMTHEME=qt5ct
	SDL_IM_MODULE="fcitx"
	XMODIFIERS="@im=fcitx"
	QT_IM_MODULE="fcitx"
	GTK_IM_MODULE="fcitx"
	EOF

	sed -i "s#shuangpin:True#shuangpin:False#g" ~/.config/fcitx/profile
	sed -i "s#pinyin:True,#pinyin:True,#g" ~/.config/fcitx/profile
	sed -i "s#EnabledIMList=#EnabledIMList=pinyin:True,#g" ~/.config/fcitx/profile
	echo "TheInputMethod=1" >> $CONFIG
	
	cat <<-EOF>> ~/.bashrc
	if [ "\$TERM"="linux" ] ;then 
		#export LANGUAGE=en_US 
		echo ""
	fi 
	EOF
	
	##设置面板图标
	mkdir -p ~/.icons
	wget https://raw.githubusercontent.com/WindowHZT/termux-ubuntu2004/main/mix/ubuntu-logo-icon.png -O /tmp/ubuntu-logo-icon.png
	#wget gitee.com/djyd/termux-ubuntu2004/raw/main/mix/ubuntu-logo-icon.png	 -O /tmp/ubuntu-logo-icon.png
	
	cat<<-EOF > "/usr/share/applications/ubuntu.desktop"
	[Desktop Entry]
	Version=1.0
	Name=ubuntu
	StartupNotify=true
	OnlyShowIn=XFCE;
	X-AppStream-Ignore=True
	Exec=/usr/local/bin/ubuntu
	Terminal=true
	X-MultipleArgs=false
	Type=Application
	Icon=/tmp/ubuntu-logo-icon.png
	EOF
	
	sudo chmod 644 /usr/share/applications/ubuntu.desktop

	if [ -f /etc/dpkg/dpkg.cfg.d/excludes ] || [ -f /etc/dpkg/dpkg.cfg.d/excludes.dpkg-tmp ]; then
	    if [ -f /etc/dpkg/dpkg.cfg.d/excludes ]; then
 	       mv /etc/dpkg/dpkg.cfg.d/excludes /etc/dpkg/dpkg.cfg.d/excludes.dpkg-tmp
		fi

		apt-get update -y
	 	apt-get upgrade -y
		dpkg -S /usr/share/man/ |sed 's|, |\n|g;s|: [^:]*$||' | DEBIAN_FRONTEND=noninteractive xargs apt-get install --reinstall -y
		dpkg --verify --verify-format rpm | awk '/..5......   \/usr\/share\/doc/ {print $2}' | sed 's|/[^/]*$||' | sort |uniq \
 	        | xargs dpkg -S | sed 's|, |\n|g;s|: [^:]*$||' | uniq | DEBIAN_FRONTEND=noninteractive xargs apt-get install --reinstall -y
		dpkg --verify --verify-format rpm | awk '/..5......   \/usr\/share\/locale/ {print $2}' | sed 's|/[^/]*$||' | sort |uniq \
			| xargs dpkg -S | sed 's|, |\n|g;s|: [^:]*$||' | uniq | DEBIAN_FRONTEND=noninteractive xargs apt-get install --reinstall -y
    
		if dpkg --verify --verify-format rpm | awk '/..5......   \/usr\/share\/doc/ {exit 1}'; then
			rm /etc/dpkg/dpkg.cfg.d/excludes.dpkg-tmp
		else
			dpkg --verify --verify-format rpm | awk '/..5......   \/usr\/share\/doc/ {print " " $2}'
		fi
	fi



	if  [ "$(dpkg-divert --truename /usr/bin/man)" = "/usr/bin/man.REAL" ]; then
		rm -f /usr/bin/man
		dpkg-divert --quiet --remove --rename /usr/bin/man
	fi
	rm -f /etc/update-motd.d/60-unminimize

}



if [ ! -e $CONFIG  ];then

	_xfce
	_DPI
	service dbus start
	_start
	
	#添加面板数组
	xfconf-query -c xfce4-panel -np /panels/panel-2/plugin-ids -t 'int' -s 15 -t 'int' -s 16 -t 'int' -s 17 -t 'int' -s 18 -t 'int' -s 19 -t 'int' -s 20 -t 'int' -s 34 -t 'int' -s 33 -t 'int' -s 21 -t 'int' -s 22
	
	##增加ubuntu
	xfconf-query -c xfce4-panel -np "/plugins/plugin-33" -t 'string' -s "launcher"
	xfconf-query -c xfce4-panel -np "/plugins/plugin-33/items" -t 'string' -a -s "ubuntu.desktop"
	
	##增加截图
	xfconf-query -c xfce4-panel -np "/plugins/plugin-34" -t 'string' -s "launcher"
	xfconf-query -c xfce4-panel -np "/plugins/plugin-34/items" -t 'string' -a -s "xfce4-screenshooter.desktop"

	##设置状态栏图标
	xfconf-query -c xfce4-panel -np '/plugins/plugin-1/button-icon' -t 'string' -s "/tmp/ubuntu-logo-icon.png"
	##设置状态栏大小
	xfconf-query -c xfce4-panel -np '/panels/panel-1/icon-size' -t 'int' -s 20
	##设置plank面板图标大小
	xfconf-query -c xfce4-panel -np '/panels/panel-2/size' -t 'int' -s 100
	##设置字体大小
	xfconf-query -c xsettings -np '/Xft/DPI' -t 'int' -s 200
	##设置桌面图标大小
	xfconf-query -c xfce4-desktop -np '/desktop-icons/icon-size' -t 'int' -s 100
	
	echo "284684.56 513853.46" > /proc/uptime
	echo "0.54 0.41 0.30 1/931 370386" >/proc/loadavg
:<<EO
	msg $red "开始汉化xfce4桌面^_^"
	if [ -f /etc/dpkg/dpkg.cfg.d/excludes ] || [ -f /etc/dpkg/dpkg.cfg.d/excludes.dpkg-tmp ]; then
	    if [ -f /etc/dpkg/dpkg.cfg.d/excludes ]; then
 	       sudo  mv /etc/dpkg/dpkg.cfg.d/excludes /etc/dpkg/dpkg.cfg.d/excludes.dpkg-tmp
		fi

		sudo apt-get update -y
	 	sudo apt-get upgrade -y
		sudo dpkg -S /usr/share/man/ |sed 's|, |\n|g;s|: [^:]*$||' | DEBIAN_FRONTEND=noninteractive xargs sudo apt-get install --reinstall -y
		sudo dpkg --verify --verify-format rpm | awk '/..5......   \/usr\/share\/doc/ {print $2}' | sed 's|/[^/]*$||' | sort |uniq \
 	        | xargs sudo dpkg -S | sed 's|, |\n|g;s|: [^:]*$||' | uniq | DEBIAN_FRONTEND=noninteractive xargs sudo apt-get install --reinstall -y
		sudo dpkg --verify --verify-format rpm | awk '/..5......   \/usr\/share\/locale/ {print $2}' | sed 's|/[^/]*$||' | sort |uniq \
			| xargs sudo dpkg -S | sed 's|, |\n|g;s|: [^:]*$||' | uniq | DEBIAN_FRONTEND=noninteractive xargs sudo apt-get install --reinstall -y
    
		if sudo dpkg --verify --verify-format rpm | awk '/..5......   \/usr\/share\/doc/ {exit 1}'; then
			sudo rm /etc/dpkg/dpkg.cfg.d/excludes.dpkg-tmp
		else
			sudo dpkg --verify --verify-format rpm | awk '/..5......   \/usr\/share\/doc/ {print " " $2}'
		fi
	fi

	if  [ "$(sudo dpkg-divert --truename /usr/bin/man)" = "/usr/bin/man.REAL" ]; then
		sudo rm -f /usr/bin/man
		sudo dpkg-divert --quiet --remove --rename /usr/bin/man
	fi
	sudo rm -f /etc/update-motd.d/60-unminimize
EO

	startTime=`cat /data/data/com.termux/files/home/Time`
	rm -rf /data/data/com.termux/files/home/Time
	endTime=`date +"%Y-%m-%d %H:%M:%S"`
	st=`date -d  "$startTime" +%s`
	et=`date -d  "$endTime" +%s`
	sumTime=$(($et-$st))
	
	echo -e "\n\n\t安装ubuntu20.04总耗时 : `echo $sumTime/60 | bc` Minutes."
	echo -e "$red 按下回车关机，重新打开软件即可冲浪🏄$white"
	read op
	kill -9 `sudo ps -ef | grep '/data/data/com.termux/files/usr/bin/bash -l' | grep -v grep | awk '{print $2}'`

fi

case $1 in
	"start")  ##启动vnc
		_start
		;;
	"stop")  ##停止vnc
		_stop
		;;
	"changeDPI")  ##改变vnc分辨率
		_DPI
		;;
	"changePWD")  ##改变vnc密码
		_PWD
		;;
	*)
		echo -e "\tvnc 帮助文档"
		echo -e "\t(1)使用命令 vnc start 启动vnc服务"
		echo -e "\t(2)使用命令 vnc stop 停止vnc服务"
		echo -e "\t(3)使用命令 vnc changeDPI 更改vnc分辨率"
		echo -e "\t(4)使用命令 vnc changePWD 更改vnc密码"
		;;
esac