#!/bin/bash
#字体颜色
red="\e[31;1m"      #红
green="\e[32;1m"   #绿
yellow="\e[33;1m"  #黄
blue="\e[34;1m"    #蓝
purple="\e[35;1m"    #紫红
cyanine="\e[36;1m"    #青蓝
white="\e[0m"

CONFIG=/usr/local/bin/.config

msg() { clear;echo -e "\n\t\t$blue[*]$white$1$2$white\n" ;:;}  ##自定义通告颜色




_login(){
	i=0
	str=""
	label=('|' '/' '-' '\\')
	index=0
	while [ $i -le 20 ]
	do
		let index=i%4
		let jinshu=$i*5
		printf "\e[0m\e[32m[%-20s]\e[0m\e[0;32m[%c]\e[1;0m\e[0;35m[%-3d%%]\e[1;0m\r" $str ${label[$index]} $jinshu
		let i++
		str+="#"
		sleep 0.1
	done
	echo
}

_start(){
	[ ! -e "/data/data/com.termux/files/home/storage/shared/MTS" ]&&mkdir /data/data/com.termux/files/home/storage/shared/MTS
	[ ! -L "`echo ~/Desktop/MTS`" ]&&ln -s /data/data/com.termux/files/home/storage/shared/MTS ~/Desktop/
	if [ ! -e "`echo ~/Desktop/MTS/说明.txt`" ];then
		touch ~/Desktop/MTS/说明.txt
		cat <<-EOF >~/Desktop/MTS/说明.txt
		PS：1.这个MTS目录是连接到手机存储目录的交换区。
			 2.方便非Root用户存取文件，和交换文件。
			 3.每一次开机都会自动创建这个目录，不用担心它被删除。（即使删了下次开机时也会恢复）
			 
		使用方法：step1.在你手机自带的文件管理器找到 MTS 这个目录。
				   step2.把你下载的刘德华最新歌曲mp3文件，复制一份到这个目录。
				   step3.打开你的ubuntu系统，在桌面点击 MTS 目录就可以看见你的mp3歌曲了。
				   
		注意：同样的，你也可以把ubuntu里面的办公文件移动到 MTS 这个目录，然后去你手机文
			  件管理器就可以轻松获取到你的办公文件了
			  
		优点：解决了虚拟机与物理机文件交换繁杂的问题。
		EOF
	fi
	
	vncserver -kill :1  > /dev/null 2>&1
	source $CONFIG
	msg $red "VNC服务器启动ing…默认密码为$USER的帐号密码"
	LD_PRELOAD=/lib/aarch64-linux-gnu/libgcc_s.so.1 vncserver -localhost no -depth 24 -name remote-desktop $GEO :$PORT
	
	_login
	msg $green "ubuntu20.04开机完毕·欢迎~"
	echo -e "\t$red获取更多帮助请使用命令 ubuntu$white"
}


_stop(){
	USER=$(whoami)
	msg $red "VNC服务列表如下："
	vncserver -list
	echo -n "输入需要杀死的端口号(示例:3):"
	read pt
	echo " "
	echo "已杀死的端口 $pt"
	vncserver -kill :$pt
	rm -rf /tmp/.X$pt-lock
	rm -rf /tmp/.X11-unix/X$pt
}


_PWD(){
	read -sp '请提供一个新的VNC密码: ' PASSWORD
	vncpasswd -f <<<"$PASSWORD\n$PASSWORD" > $HOME/.vnc/passwd
	msg $green "VNC登录密码已修改！"
}




_DPI(){
	export USER=$(whoami)
	export LC_ALL="zh_CN.UTF-8"
	HEIGHT=0
	WIDTH=0
	CHOICE_HEIGHT=5
	BACKTITLE="VNC 分辨率选择"
	TITLE="vncserver-start"
	MENU="请选择你的分辨率"
	export PORT=1
	
	OPTIONS=(
         1 "QHD 2k画质(2560x1600)"
         2 "FHD 1080p画质(1920x1080)"
         3 "HD-ready 高清画质(1280x720)"
         4 "自动画质"
         5 "自定义画质/端口")

	CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

	clear
	case $CHOICE in
        1)
            echo "你选择了QHD 2k画质(2560x1600)"
            echo 'GEO="-geometry 2560x1600"' > $CONFIG
            echo 'PORT="1"' >> $CONFIG
            ;;
        2)
            echo "你选择了FHD 1080p画质(1920x1080)"
            echo 'GEO="-geometry 1920x1080"' > $CONFIG
            echo 'PORT="1"' >> $CONFIG
            ;;
        3)
            echo "你选择了HD-ready 高清画质(1280x720)"
            echo 'GEO="-geometry 1280x720"' > $CONFIG
            echo 'PORT="1"' >> $CONFIG
            ;;
        4)
            echo "你选择了自动画质"
            echo 'GEO=""' > $CONFIG
            echo 'PORT="1"' >> $CONFIG
            ;;
        5)
            echo "您选择手动提供 分辨率/端口"
            echo "输入您的自定义分辨率格式WIDTHxHEIGHT即1920x1200"
            echo -ne "分辨率：" ""
            read custom
            echo "输入您的自定义端口，即2" 
            echo -ne "端口：" ""
            read port
            echo "GEO=\"-geometry $custom\"" > $CONFIG
            echo "PORT=$port" >> $CONFIG
            ;;
	esac	
}

_xfce(){
	msg $red "安装xfce桌面"
	echo -e "$red请输入root用户的密码：$white"
	sudo apt purge dialog -y

	sudo apt install software-properties-common -y
	sudo add-apt-repository ppa:xubuntu-dev/staging -y
	sudo apt-get update
	sudo apt install udisks2 -y
	echo "" > /var/lib/dpkg/info/udisks2.postinst
	sudo dpkg --configure -a
	sudo apt-mark hold udisks2
	sudo apt install keyboard-configuration -y
	sudo apt install tzdata -y
	sudo apt install sudo wget nano inetutils-tools dialog -y
	sudo apt install xfce4 xfce4-goodies xfce4-terminal exo-utils tigervnc-standalone-server tigervnc-common dbus-x11 ffmpeg  language-pack-en --no-install-recommends -y
	#sudo apt --fix-broken install
	sudo apt clean git -y
	
	mkdir -p ~/.vnc
	USER=`cat /usr/local/bin/.USER`
	vncpasswd -f <<< `cat /usr/local/bin/.PASSWORD` > "/home/$USER/.vnc/passwd"
	rm -rf /usr/local/bin/.PASSWORD

	#/usr/bin/vncpasswd -f <<<"$PASSWORD\n$PASSWORD" > "/home/$USER/.vnc/passwd"
	#vncpasswd -f <<<"$PASSWORD"$'\n'"$PASSWORD" > /root/.vnc/passwd 

	cat <<-EOF > ~/.vnc/xstartup
	#!/bin/bash
	[ -r \$HOME/.Xresources ] && xrdb \$HOME/.Xresources
	export PULSE_SERVER=127.0.0.1
	XAUTHORITY=\$HOME/.Xauthority
	export XAUTHORITY
	LANG=en_US.UTF-8
	export LANG
	echo \$\$ > /tmp/xsession.pid
	dbus-launch --exit-with-session startxfce4 &
	EOF
	
	
	sudo apt-get install fonts-wqy-microhei -y

	echo "export DISPLAY=\":1\"" >> /etc/profile
	source /etc/profile
}



if [ ! -e $CONFIG  ];then

	_xfce
	echo " " > $CONFIG
	_DPI
	export LC_ALL=""
	##设置面板图标
	mkdir -p ~/.icons
	wget https://raw.githubusercontent.com/WindowHZT/termux-ubuntu2004/main/mix/ubuntu-logo-icon.png -O ~/.icons/ubuntu-logo-icon.png
	_start
	
	##设置状态栏图标
	xfconf-query -c xfce4-panel -np '/plugins/plugin-1/button-icon' -t 'string' -s '/home/hzt/.icons/ubuntu-logo-icon.png'
	##设置状态栏大小
	xfconf-query -c xfce4-panel -np '/panels/panel-1/icon-size' -t 'int' -s 20
	##设置plank面板图标大小
	xfconf-query -c xfce4-panel -np '/panels/panel-2/size' -t 'int' -s 60
	##设置字体大小
	xfconf-query -c xsettings -np '/Xft/DPI' -t 'int' -s 135
	##设置桌面图标大小
	xfconf-query -c xfce4-desktop -np '/desktop-icons/icon-size' -t 'int' -s 65
	
	startTime=`cat /data/data/com.termux/files/home/Time`
	rm -rf /data/data/com.termux/files/home/Time
	endTime=`date +"%Y-%m-%d %H:%M:%S"`
	st=`date -d  "$startTime" +%s`
	et=`date -d  "$endTime" +%s`
	sumTime=$(($et-$st))
	
	echo -e "\n\n\t安装ubuntu20.04总耗时 : $sumTime second."
	exit
fi


case $1 in
	"start")  ##启动vnc
		_start
		;;
	"stop")  ##停止vnc
		_stop
		;;
	"changeDPI")  ##改变vnc分辨率
		_DPI
		;;
	"changePWD")  ##改变vnc密码
		_PWD
		;;
	*)
		echo -e "\tvnc 帮助文档"
		echo -e "\t(1)使用命令 vnc start 启动vnc服务"
		echo -e "\t(2)使用命令 vnc stop 停止vnc服务"
		echo -e "\t(3)使用命令 vnc changeDPI 更改vnc分辨率"
		echo -e "\t(4)使用命令 vnc changePWD 更改vnc密码"
		;;
esac